= Tiles

== Summary

Android Live Wallpaper in Java using OpenGL ES 2.0, texture mapping.

All you can see here is work in progress, for stable Version go to Google Play
(Free Beta App: https://play.google.com/store/apps/details?id=pit.opengles).
If you want to build it for yourself, you can do so
. Install Android Studio
. File->New->Import Project
. Build APK
. Copy to your phone(Minimum API 21(Android 5.0)), enjoy :)


Feature wishes are welcome (github ticket)

Big shoutout to the guys from http://www.learnopengles.com for the good explanations to the different OpenGL ES topics; learned a lot from them!


== Features
- [x] colored radio buttons for selection
- [x] imprint and copyright :-)
- [x] two different paths the light follows (straight and wave)
- [x] light speed configurable
- [x] settings stored when reconfiguring the live wallpaper
- [x] admob support to help me get some support for my next test phone (Pixel X?) ;-)


== Roadmap (unsorted)
* [ ] configuration to hide icon in app drawer
* [ ] new real physical effect moves
* [ ] load phone images to be used as background
* [ ] ....
