= Tiles

== Summary

Android Live Wallpaper in Java using OpenGL ES 2.0, texture mapping.

All you can see here is work in progress, for stable Version go to Google Play
(Free App: https://play.google.com/store/apps/details?id=pit.opengles).
If you want to build it for yourself, you can do so
. Install Android Studio
. File->New->Import Project
. Build APK
. Copy to your phone(Minimum API 21(Android 5.0)), enjoy :)
(Console build with gradle should also be possible)


Feature wishes are welcome (github ticket)

Big shoutout to the guys from http://www.learnopengles.com for the good explanations to the different OpenGL ES topics; learned a lot from them!


== Features
- [x] colored dropdown menu for selection
- [x] seven different backgrounds (more to come)
- [x] imprint and copyright :-)
- [x] different paths the light follows (straight, 8 and random movement)
- [x] light speed configurable
- [x] working optimized parallax effect
- [x] settings stored when reconfiguring the live wallpaper
- [x] admob support to help me get some support for my next test phone (Pixel X?) ;-)
- [x] ui support of many different sized screens (Phone, Tablet) and differen aspect ratios

== Next Big Thing ;-)
* [ ] light specific effects (flicker, glow)
* [ ] more backgrounds in general

== Roadmap (unsorted)
* [ ] pro version for fans
* [ ] new real physical effect moves
* [ ] even better support for different aspect ratios (because 16:9 is too boring for all the smartphone manifacturers^^)
* [ ] ....
